name = "medium"
compatibility_date = "2023-12-01"

 [vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiYTljMTBmZDktMjEwYy00YWVkLWFmYzAtNTEwYzcyZWQ1ZDAzIiwidGVuYW50X2lkIjoiMTdlOGJkNjMzNGY3MmI3ZTAwNTRjMzk2OGRjMTEzZWY3YTlhZGQxNjBjZGY2NjlkNTYwOWRjZjcwODk2OTlhNiIsImludGVybmFsX3NlY3JldCI6ImNhYzE3YjEzLTEyZjktNDgxNy04OWFjLWUyOGY0YTEwNmI2ZCJ9.hcfZZCh090qMd2VG8ibPwjO8HCFGK26iSUnW0Bf3I2I"
JWT_SECRET = "asdasd"




